version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tool-roll-dice"
s3_prefix = "tool-roll-dice"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true

[default.build]
[default.build.parameters]
cached = true
parallel = true

