AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Root SAM Template for AI Game - Infrastructure

Resources:
  # Lambda Functions Stack
  LambdaStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./lambda/tool-roll-dice/template.yaml

  # Agent Master - Main AI Agent
  AgentMasterStack:
    Type: AWS::Serverless::Application
    DependsOn: LambdaStack
    Properties:
      Location: ./agents/agent-master/template.yaml
      Parameters:
        FoundationModel: anthropic.claude-3-sonnet-20240229-v1:0
        AgentInstruction: You are AgentMaster, a helpful AI assistant that can help users with various tasks.
        ToolRollDiceLambdaArn: !GetAtt LambdaStack.Outputs.ToolRollDiceFunctionArn

Outputs:
  # Lambda Outputs
  ToolRollDiceFunctionArn:
    Description: The ARN of the ToolRollDice Lambda Function
    Value: !GetAtt LambdaStack.Outputs.ToolRollDiceFunctionArn
    Export:
      Name: !Sub ${AWS::StackName}-ToolRollDiceFunctionArn
  
  ToolRollDiceFunctionName:
    Description: The Name of the ToolRollDice Lambda Function
    Value: !GetAtt LambdaStack.Outputs.ToolRollDiceFunctionName
    Export:
      Name: !Sub ${AWS::StackName}-ToolRollDiceFunctionName

  # Agent Outputs
  AgentMasterId:
    Description: The ID of the AgentMaster Bedrock Agent
    Value: !GetAtt AgentMasterStack.Outputs.AgentId
    Export:
      Name: !Sub ${AWS::StackName}-AgentMasterId
  
  AgentMasterArn:
    Description: The ARN of the AgentMaster Bedrock Agent
    Value: !GetAtt AgentMasterStack.Outputs.AgentArn
    Export:
      Name: !Sub ${AWS::StackName}-AgentMasterArn
  
  AgentMasterAliasId:
    Description: The ID of the AgentMaster Alias
    Value: !GetAtt AgentMasterStack.Outputs.AgentAliasId
    Export:
      Name: !Sub ${AWS::StackName}-AgentMasterAliasId
  
  AgentMasterAliasArn:
    Description: The ARN of the AgentMaster Alias
    Value: !GetAtt AgentMasterStack.Outputs.AgentAliasArn
    Export:
      Name: !Sub ${AWS::StackName}-AgentMasterAliasArn

